import { AppProps } from '../node_modules/next/dist/shared/lib/router/router';
import '../styles/globals.css';

import Head from '../node_modules/next/head';

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return <>
          <Head>
            <title>MyTop - our best top</title>
            <meta name="description" content="Generated by create next app" />
            <link key={2} rel="icon" href="/favicon.ico" />
          </Head>
            <Component {...pageProps} />
  </>;
}

export default MyApp;