import { AppProps } from '../node_modules/next/dist/shared/lib/router/router';
import '../styles/globals.css';

import Head from '../node_modules/next/head';

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return <>
          <Head>
            <title>MyTop - our best top</title>
            <meta name="description" content="Generated by create next app" />
            <link key={2} rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/>
            <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300&family=Noto+Sans:wght@300;400;500;700&family=Roboto+Mono:ital@1&family=Roboto:ital,wght@1,100&display=swap" rel="stylesheet"></link>
          </Head>
            <Component {...pageProps} />
            
        </>;
}

export default MyApp;